import type { Metadata } from "next";
import { Nunito } from "next/font/google";

import LinkedinSvg from "/public/svgs/linkedin.svg";
import GitHubSvg from "/public/svgs/github.svg";

const nunito = Nunito({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nunito",
});

import "./globals.css";
import { ThemeProvider } from "./theme-provider";

import NavBar from "./components/NavBar";

export const metadata: Metadata = {
  title: "Portfolio | Natanael Silva",
  description: "Generated by create next app",
  icons: {
    icon: "/profile_img.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //suppressHydrationWarning - inject in html tag later
  return (
    <html lang="en" className={nunito.variable} suppressHydrationWarning>
      <body
        className={`dark:bg-[#191919] bg-[#fefefe] dark:text-[#989899] text-[#7E7E83] transition duration-500 ease-in-out my-0 mx-auto px-6 max-w-[448px] md:max-w-[1000px] md:px-20`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <header>
            <NavBar />
          </header>
          <main>{children}</main>
          <footer className="border-t-[1px] flex-col md:flex-row py-4 dark:border-[#989899] flex border-[#3c3c43] items-center justify-between font-semibold">
            <div>© Copyright Natanael 2023. All the rights reserved.</div>
            <div className="flex py-3">
              Find me on:
              <a href="https://github.com/natanael-silv">
                <GitHubSvg className="mx-4 fill=[#6a6a64]" />
              </a>
              <a href="https://www.linkedin.com/in/natanael-silvas/">
                <LinkedinSvg className="mx-4 fill=[#6a6a64]" />
              </a>
            </div>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
