import type { Metadata } from "next";
import { Nunito } from "next/font/google";

import { notFound } from "next/navigation";
import { NextIntlClientProvider, useMessages } from "next-intl";

const nunito = Nunito({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nunito",
});

type Props = {
  children: ReactNode;
  params: { locale: string };
};

import "./globals.css";
import { ThemeProvider } from "../theme-provider";

import NavBar from "../components/NavBar";
import { ReactNode } from "react";
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "Portfolio | Natanael Silva",
  description: "Generated by create next app",
  icons: {
    icon: "/profile_img.png",
  },
};

const locales = ["en", "pt"];

export default function RootLayout({ children, params: { locale } }: Props) {
  const messages = useMessages();
  if (!locales.includes(locale as any)) notFound();
  //suppressHydrationWarning - inject in html tag later
  return (
    <html lang={locale} className={nunito.variable} suppressHydrationWarning>
      <body
        className={`dark:bg-[#191919] bg-[#fefefe] dark:text-[#989899] text-[#7E7E83] transition duration-500 ease-in-out my-0 mx-auto px-6 max-w-[448px] md:max-w-[1000px] md:px-20`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <header>
              <NavBar />
            </header>
            <main>{children}</main>
            <Footer />
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
